package com.smart.app;
final class DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider implements javax.inject.Provider {
    private final com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl a;
    private final com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl b;
    private final com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl c;
    private final int d;

    DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl p1, com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl p2, com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl p3, int p4)
    {
        this.a = p1;
        this.b = p2;
        this.c = p3;
        this.d = p4;
        return;
    }

    public Object get()
    {
        switch (this.d) {
            case 0:
                return new com.thingclips.smart.scene.device.datapoint.ActionDatapointListViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.G(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.H(this.c), this.a.w(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c));
            case 1:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_89 = new com.thingclips.smart.scene.home.automation.AutomationListViewModel;
                v1_89(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.J(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.K(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.L(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.M(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.O(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.c(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.P(this.c));
                return v1_89;
            case 2:
                return new com.thingclips.smart.scene.condition.position.ChooseCityViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Q(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.R(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.S(this.c), dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideContextFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)));
            case 3:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_85 = new com.thingclips.smart.scene.action.linkage.ChooseLinkageViewModel;
                v1_85(this.a.c(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.J(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.T(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.L(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.U(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c));
                return v1_85;
            case 4:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_83 = new com.thingclips.smart.scene.device.datapoint.ConditionDatapointListViewModel;
                v1_83(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.V(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.W(this.c), this.a.z(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.X(this.c));
                return v1_83;
            case 5:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_81 = new com.thingclips.smart.scene.construct.guide.ConstructGuideViewModel;
                v1_81(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Y(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Z(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.a0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.b0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), this.a.z(), this.a.v(), dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideContextFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)));
                return v1_81;
            case 6:
                return new com.thingclips.smart.scene.action.delay.DelayViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), this.a.w());
            case 7:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_77 = new com.thingclips.smart.scene.device.choose.DeviceChooseViewModel;
                v1_77(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.c0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.d0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.e0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.f0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.g0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.h0(this.c), ((com.thingclips.smart.scene.api.ISceneService) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.g0(this.a).get()));
                return v1_77;
            case 8:
                return new com.thingclips.smart.scene.home.device.DeviceScenesVieModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.i0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.j0(this.c), this.a.k(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.c(this.b));
            case 9:
                return new com.thingclips.smart.light.scene.plug.dimming.viewmodel.DimmingViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneDimmingRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.h0(this.a).get()));
            case 10:
                return new com.thingclips.smart.scene.construct.extension.EffectivePeriodViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Q(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.l0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.S(this.c));
            case 11:
                return new com.thingclips.smart.scene.record.exception.ExceptionDetailViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.m0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.n0(this.c));
            case 12:
                return new com.thingclips.smart.scene.home.execute.ExecuteResultViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.o0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.d(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.p0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.q0(this.c));
            case 13:
                return new com.thingclips.smart.scene.condition.geofencing.GeofencingModeViewModel(this.a.z(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c));
            case 14:
                return new com.thingclips.smart.scene.construct.extension.IconStyleViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.r0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.s0(this.c));
            case 15:
                return new com.thingclips.smart.scene.home.invalid.InvalidSceneViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.M(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.t0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.u0(this.c));
            case 16:
                return new com.thingclips.smart.light.scene.plug.location.viewmodel.LightSceneAreaViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneLocationRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.i0(this.a).get()));
            case 17:
                return new com.thingclips.smart.light.scene.plug.viewmodel.LightSceneCreateVM(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneIconRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.j0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneVasRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.k0(this.a).get()));
            case 18:
                return new com.thingclips.smart.light.scene.plug.location.viewmodel.LightSceneMapViewModel(dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideApplicationFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)), ((com.thingclips.smart.light.scene.api.repository.LightSceneLocationRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.i0(this.a).get()));
            case 19:
                return new com.thingclips.smart.light.scene.plug.viewmodel.LightSceneStepAreaViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneRoomRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.l0(this.a).get()));
            case 20:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_45 = new com.thingclips.smart.light.scene.plug.viewmodel.LightSceneStepNormalSceneViewModel;
                v1_45(dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideApplicationFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneIconRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.j0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneVasRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.k0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneDetailRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.m0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneRoomRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.l0(this.a).get()));
                return v1_45;
            case 21:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_43 = new com.thingclips.smart.light.scene.plug.viewmodel.LightSceneStepRhythmSceneViewModel;
                v1_43(dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideApplicationFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneIconRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.j0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneDetailRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.m0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneRoomRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.l0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneRhythmRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.n0(this.a).get()), ((com.thingclips.smart.light.scene.api.repository.LightSceneLocationRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.i0(this.a).get()));
                return v1_43;
            case 22:
                return new com.thingclips.smart.light.scene.plug.viewmodel.LightSceneStepSaveViewModel(dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideApplicationFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneIconRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.j0(this.a).get()));
            case 23:
                return new com.thingclips.smart.light.scene.plug.viewmodel.LightSceneStepSceneTypeViewModel(dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideApplicationFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k0(this.c), ((com.thingclips.smart.light.scene.api.repository.LightSceneRhythmRepository) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.n0(this.a).get()));
            case 24:
                return new com.thingclips.smart.scene.action.linkage.LinkageTypeViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.v0(this.c));
            case 25:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_34 = new com.thingclips.smart.scene.condition.member.LockMemberViewModel;
                v1_34(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.w0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.x0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.y0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), this.a.z());
                return v1_34;
            case 26:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_32 = new com.thingclips.smart.scene.home.manual.ManualListViewModel;
                v1_32(this.a.c(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.z0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.T(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.t0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.c(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.O(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.P(this.c));
                return v1_32;
            case 27:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_30 = new com.thingclips.smart.scene.action.push.MessagePushViewModel;
                v1_30(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.A0(this.c), this.a.w(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.B0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.C0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.D0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.E0(this.c));
                return v1_30;
            case 28:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_27 = new com.thingclips.smart.scene.construct.detail.NormalSceneDetailViewModel;
                v1_27(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.W(this.c), this.a.r(), this.a.v(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.F0(this.c), this.a.g(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.G0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Z(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.H0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.d(this.b), this.a.z(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Y(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.J0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.K0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.s0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.e(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.L0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.M0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.O0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.P0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.r0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Q0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.R0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.b(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.a0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.c(this.c));
                return v1_27;
            case 29:
                return new com.thingclips.smart.scene.home.offline.OfflineDeviceListModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.d(this.c));
            case 30:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_24 = new com.thingclips.smart.scene.recommend.detail.RecommendDetailViewModel;
                v1_24(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.e(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.f(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.g(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.A0(this.c), this.a.n(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.h(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.i(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.D0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.E0(this.c), this.a.r(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Z(this.c), this.a.v(), this.a.w(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.b(this.c));
                return v1_24;
            case 31:
                return new com.thingclips.smart.scene.recommend.list.RecommendListViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.O(this.c), this.a.n());
            case 32:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_20 = new com.thingclips.smart.scene.home.dashboard.SceneDashboardDPCViewModel;
                v1_20(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.j(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.j0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.l(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.f(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.m(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.n(this.c), this.a.n(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.c(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.o(this.c), com.thingclips.smart.scene.core.di.AppModule_ProvidesIoDispatcherFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.W(this.a)));
                return v1_20;
            case 33:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_19 = new com.thingclips.smart.scene.home.dashboard.SceneDashboardViewModel;
                v1_19(this.a.c(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.T(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.k(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.l(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.m(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.n(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.c(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.o(this.c));
                return v1_19;
            case 34:
                return new com.thingclips.smart.scene.home.dashboard.SceneDashboardWholeHouseViewModel(this.a.k(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.c(this.b));
            case 35:
                return new com.thingclips.smart.scene.construct.extension.SceneExtensionInfoViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.J0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.s0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.r0(this.c));
            case 36:
                return com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.w(this.c, com.thingclips.smart.scene.home.tab.SceneHomeViewModel_Factory.b(this.a.k(), this.a.n(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.p(this.c), this.a.q(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.q(this.c), this.a.g(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.r(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.s(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.t(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.u(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.v(this.c), ((com.thingclips.smart.scene.api.ISceneService) com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.g0(this.a).get())));
            case 37:
                return new com.thingclips.smart.scene.record.list.SceneLogsViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.x(this.c), this.a.g(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.y(this.c));
            case 38:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_10 = new com.thingclips.smart.scene.home.sort.SceneSortViewModel;
                v1_10(this.a.c(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.J(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.T(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.L(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.z(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Q0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.u0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.A(this.c));
                return v1_10;
            case 39:
                return new com.thingclips.smart.scene.condition.timer.TimerViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), this.a.z(), dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideContextFactory.b(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$SingletonCImpl.H(this.a)));
            case 40:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_7 = new com.thingclips.smart.scene.condition.weather.detail.WeatherDetailViewModel;
                v1_7(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Q(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.B(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.C(this.c), this.a.z(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.X(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.W(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.S(this.c));
                return v1_7;
            case 41:
                return new com.thingclips.smart.scene.condition.weather.WeatherListViewModel(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.D(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c));
            case 42:
                com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl v1_21 = new com.thingclips.smart.scene.construct.detail.WithoutGatewaySceneDetailViewModel;
                com.thingclips.smart.scene.construct.detail.WithoutGatewaySceneDetailViewModel v35_0 = v1_21;
                v1_21(com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.W(this.c), this.a.r(), this.a.v(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.F0(this.c), this.a.g(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.G0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Z(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.H0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.I0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.d(this.b), this.a.z(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Y(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.J0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.K0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.s0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.e(this.b), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.L0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.M0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.N0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.O0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.P0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.r0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.Q0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.E(this.c), this.a.h(), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.R0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.F(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.q(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.b(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.a0(this.c), com.smart.app.DaggerSmartApplication_HiltComponents_SingletonC$ViewModelCImpl.c(this.c));
                return v35_0;
            default:
                throw new AssertionError(this.d);
        }
    }
}
